import {mkdirSync,writeFileSync,readFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {parseArgs} from 'node:util';
import {restoreSources,leagues, type FootballDataset} from '../strategies/football.js';
import {compareFootball,comparisonTrials} from './football-comparison.js';
import {escapeHtml,csvCell} from './report.js';

const {values}=parseArgs({options:{out:{type:'string',default:'reports/football-comparison'},manifest:{type:'string'}}});
if(!values.manifest)throw new Error('Indica --manifest para reproducir fuentes verificadas sin descargar nuevos datos');
const directory=resolve(values.out!);if(existsSync(directory))throw new Error('El destino ya existe; conserva los ensayos anteriores');
const sha=(text:string|Buffer)=>createHash('sha256').update(text).digest('hex');
const protocolFile='docs/evidence/football-comparison-plan-20260906.json',protocol=JSON.parse(readFileSync(protocolFile,'utf8'));
if(JSON.stringify(protocol.trials)!==JSON.stringify(comparisonTrials))throw new Error('Los ensayos no coinciden con el protocolo');
const source=JSON.parse(readFileSync(values.manifest,'utf8')),datasets=new Map<string,FootballDataset>();
if(!Array.isArray(source.sources)||!source.sources.length)throw new Error('Manifiesto de fuentes inválido');
for(const entry of source.sources){if(!leagues.some(l=>l.id===entry.league)||datasets.has(entry.league))throw new Error('Liga inválida o duplicada');datasets.set(entry.league,restoreSources(entry,resolve('.runtime/football')));}
const result={...compareFootball(datasets),capturedAt:Date.now(),sources:source.sources,protocol,protocolSha256:sha(readFileSync(protocolFile)),sourceManifestSha256:sha(readFileSync(values.manifest)),codeHashes:Object.fromEntries(['src/strategies/football.ts','src/research/football-comparison.ts','src/research/football-comparison-cli.ts'].map(file=>[file,sha(readFileSync(file))])),costs:{pnl:null,fees:null,gas:null,reason:'Solo resultados deportivos; sin órdenes ni costes ejecutables de Polymarket.'},limitations:[...protocol.limitations,
 'Las fechas son días UTC: se excluyen resultados del mismo día y posteriores. El proveedor no acredita publicación histórica intradía ni revisiones.',
 'Calibración sobre casos comunes; intervalos Wilson marginales descriptivos sin ajuste por comparaciones múltiples ni dependencia entre partidos. Un bin con al menos 30 observaciones tampoco autoriza tamaño de apuestas.',
 'Rho ajustado por liga y día con al menos 20 marcadores bajos; intensidades fijas del estimador Poisson regularizado. Los casos insuficientes o con corrección imposible quedan en cobertura.',
],attribution:[{url:'https://football-data.co.uk/data.php',use:'Resultados y cuotas, sujetos a condiciones del proveedor; CSV originales conservados por checksum.'},{url:'https://github.com/jpmouracodex/football-mle/blob/51494de7912e3b7135ed9491f07c937b9466ea44/football_mle/likelihood.py',use:'Referencia primaria para tau y pesos temporales. Implementación propia de corrección condicional, sin importar ni ejecutar ese código.'}]};
const csv=[['league','period','model','date','home','away','actual','p_home','p_draw','p_away','closing_home','closing_draw','closing_away','sample_size','lambda_home','lambda_away','rho','rho_training','checksum'],...result.rows.map(r=>[r.league,r.period,r.model,new Date(r.date).toISOString(),r.home,r.away,r.actual,...r.probabilities,...(r.closing??['','','']),r.sampleSize,r.lh,r.la,r.rho,r.rhoTraining,r.checksum])].map(r=>r.map(csvCell).join(',')).join('\n');
const f=(n:number|null)=>n===null?'Sin muestra':n.toFixed(4),metric=(m:{n:number;brier:number|null;logLoss:number|null})=>`${m.n} / ${f(m.brier)} / ${f(m.logLoss)}`;
const html=`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Botpoly · Comparación de fútbol</title><style>body{background:#101018;color:#eee;font:16px/1.6 system-ui;padding:24px;max-width:1200px;margin:auto}h1,h2{color:#b9a9ff}pre{white-space:pre-wrap;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #454552;text-align:left}.scroll{overflow:auto}summary{cursor:pointer}:focus-visible{outline:2px solid #b9a9ff}</style><h1>Fútbol: modelos y calibración por liga</h1><p>Desarrollo 2023/24–2024/25 y evaluación cronológica 2025/26. Cuatro variantes fijadas, sin seleccionar un modelo para producción. Menor Brier y log-loss es mejor. Sin PnL ni aprobación para dimensionar nuevas apuestas.</p><p>Dixon–Coles se evalúa como corrección de marcadores bajos sobre las tasas Poisson existentes: no es un ajuste conjunto de ataque y defensa.</p><h2>Comparación: n / Brier / log-loss</h2><div class="scroll" tabindex="0" aria-label="Comparación de modelos"><table><thead><tr><th>Periodo / liga</th><th>Modelo</th><th>Casos propios</th><th>Mismos partidos</th><th>Modelo con cuotas</th><th>Cuotas sin margen</th></tr></thead><tbody>${result.summary.map(s=>`<tr><td>${s.period} / ${s.league}</td><td>${s.model}</td><td>${metric(s.ownCoverage)}</td><td>${metric(s.commonCases)}</td><td>${metric(s.modelWithClosing)}</td><td>${metric(s.closingReference)}</td></tr>`).join('')}</tbody></table></div><h2>Calibración: probabilidades frente a resultados</h2><p>Intervalos Wilson descriptivos; grupos con menos de 30 observaciones identificados. No son una garantía de calibración ni de rentabilidad.</p>${result.summary.map(s=>`<details><summary>${s.period} / ${s.league} / ${s.model}</summary><div class="scroll" tabindex="0" aria-label="Calibración ${s.league}"><table><thead><tr><th>Resultado</th><th>Probabilidad</th><th>n</th><th>Pronóstico medio</th><th>Frecuencia real</th><th>Wilson 95%</th><th>Muestra</th></tr></thead><tbody>${s.calibration.map(c=>`<tr><td>${['Local','Empate','Visitante'][c.outcome]}</td><td>${c.from}–${c.to}</td><td>${c.n}</td><td>${f(c.forecast)}</td><td>${f(c.observed)}</td><td>${c.observedWilson95?.map(f).join(' – ')??'Sin muestra'}</td><td>${c.status}</td></tr>`).join('')}</tbody></table></div></details>`).join('')}<h2>Limitaciones y procedencia</h2><pre>${escapeHtml(JSON.stringify({...result,summary:undefined,rows:undefined,fits:undefined},null,2))}</pre>`;
mkdirSync(directory,{recursive:true,mode:0o700});
for(const [file,body] of [['result.json',JSON.stringify(result,null,2)],['predictions.csv',csv],['report.html',html]])writeFileSync(resolve(directory,file),body,{mode:0o600,flag:'wx'});
const manifest={schema:1,kind:result.kind,capturedAt:result.capturedAt,periods:result.periods,sources:result.sources,protocolSha256:result.protocolSha256,codeHashes:result.codeHashes,files:Object.fromEntries(['result.json','predictions.csv','report.html'].map(file=>[file,sha(readFileSync(resolve(directory,file)))]))};
writeFileSync(resolve(directory,'manifest.json'),JSON.stringify(manifest,null,2),{mode:0o600,flag:'wx'});
console.log(JSON.stringify({report:directory,rows:result.rows.length,summary:result.summary.filter(s=>s.league==='all').map(({calibration,...s})=>s)},null,2));
